### ISSUE TITLE
README

### ISSUE THREAD

**Issue by CPernet** [hbp-brain-charting/public_protocols#1]
could you please update the readme file - maybe add a description of each folder and what to find in them. Most things are self-explanatory but not all, for instance, it's not clear what the mp4 files are for or contain.

**Comment by alpinho** [comment]
I've updated the main README.md file with an overall description of the structure of the repository as well as the remaining README.md files in the subdirectories. I've also created new README.md files concerning the video annotations for each group of protocols.
